name: MXW01 Thermal Printer
version: "1.0.2"
slug: mxw01_printer
description: "Control MXW01 Bluetooth thermal printer from Home Assistant"
url: https://github.com/clementvp/mxw01-thermal-printer
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:printer
host_dbus: true
host_network: false
apparmor: false
devices:
  - /dev/bus/usb
privileged:
  - NET_ADMIN
  - NET_RAW
hassio_api: true
homeassistant_api: true
options:
  printer_mac: ""
  auto_connect: true
  print_intensity: 128
  dither_method: "floyd-steinberg"
  log_level: "info"
schema:
  printer_mac: str
  auto_connect: bool
  print_intensity: int(0,255)
  dither_method: list(floyd-steinberg|bayer|atkinson|none)
  log_level: list(debug|info|warning|error)
